# Generated by Django 3.2.5 on 2021-08-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
