# Generated by Django 3.2.5 on 2021-08-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_cartitem_redused_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='redused_price',
            new_name='reduced_price',
        ),
    ]
